{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-mvc.serviceAccountName" . }}
  labels:
{{ include "sample-mvc.labels" . | nindent 4 }}
{{- end -}}
