on:
  - workflow_dispatch

jobs:
  build-secure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - run: docker build . -t contoso.azurecr.io/k8sdemo:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: contoso.azurecr.io/k8sdemo:${{ github.sha }}
