name: "ContainerScan"

on:
  - workflow_dispatch

jobs:
  build-secure:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      - uses: Azure/container-scan@v0
        with:
          image-name: vulnerables/cve-2014-6271

#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
         
#      - name: Build WebApp
#        uses: docker/build-push-action@v2
#        with:
#          builder: ${{ steps.buildx.outputs.name }}        
#          push: false
#          context: ./src/WebApp
#          file: ./src/WebApp/Dockerfile
#          build-args: VERSION_FOLDER=fred-version
