name: "ContainerScan"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: vulnerables/cve-2014-6271
